import './globals.css'
export const metadata = {
  title: 'note2',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" href="/icon.png"></link>
        <link rel="icon" href="/icon.png" />
        <meta name="theme-color" content="#444" />
        <title>note2</title>
      </head>
      <body className='h-screen'>{children}</body>
    </html>
  )
}
