import './globals.css'
export const metadata = {
  title: 'note2',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className='h-screen'>{children}</body>
    </html>
  )
}
